### ISSUE TITLE
Grant Smith - Trees

### ISSUE THREAD

**Issue by Grant-Smith** [pennstategeog467/pennstategeog467.github.io#3]
All the data for my project has already been collected by OPP, and is visualized in their Lorax Tree Database.

My project will hopefully involve creating proportional symbols for both evergreen and deciduous trees, with height being the main variable in the symbol representation.  I'm also thinking about creating a shaded walkway layer, which would take the canopy diameter of each tree and represent the amount of shade that is cast by each tree on the sidewalks throughout campus.  This would allow students and staff to find a walkway that is most shaded during the early fall and late spring.

I should be working mostly in Mapbox Studio, and possibly a design software for creating 3D tree symbols.  In Mapbox Studio, I'll have to learn their language and how to represent symbols in their program.

**Comment by aaronpdennis** [comment]
This is great, Grant.

You should copy what you wrote for this issue and make a new issue in the repository [campus-base-map.tm2](https://github.com/pennstategeog467/campus-base-map.tm2). This is where the Mapbox Studio project for the existing base map is located. You can download the ZIP file, open it in Mapbox Studio, and then add/style your trees data as you work on it.
